### PR TITLE
Menu & Fragments

### LINKED ISSUE #163: Add menu buttons
Either add a meny to switch between views or buttons to get to the home page

### PR DESCRIPTION
**Pull request by LordRekishi**
Fix #163 

This will also add Fragments that are used so we do not need to duplicate code so much in the future. Implemented fragments on the header information and menu row

### CODE REVIEW

**Comment by LordRekishi** [comment]
Will rework this to use drop-down menu for entities

**Comment by LordRekishi** [comment]
### To sum-up what I have done in this pull:

Added a menu to the top of the pages where we can navigate to the other pages, some with drop downs that allows you to access the sub pages of different pages (for example: Show Categories and Add Category). In order for dropdowns to work I had to implement Popper which is something Bootstrap uses. I took this opportunity to also upgrade the bootstrap version we were using to the latest one.

I have also implemented Fragments so that we don't have to duplicate the menu code for every html page. I also used fragments for the header information. 

### Info:
[Navbar](https://getbootstrap.com/docs/5.1/components/navbar/?#how-it-works)
[Dropdowns](https://getbootstrap.com/docs/5.1/components/dropdowns/)
[Popper](https://popper.js.org/)
[Fragments & Menu tutorial](https://youtu.be/IeK-Imp9_Q0)

### Deployment instructions:
- Remove old containers
- Remove crimedatabase_backend image
- Run docker-compose

**Review by helenahalldiniths — CHANGES_REQUESTED** [review]
When you are logged in as a "USER" you are not supposed to be able handle/shor criminals, users or victims. In this implementation you can not view them, but you can add them. Maybe this is intentional? If so we need to change the REDME.md file to match this behavior.

**Comment by helenahalldiniths** [comment]
> When you are logged in as a "USER" you are not supposed to be able handle/shor criminals, users or victims. In this implementation you can not view them, but you can add them. Maybe this is intentional? If so we need to change the REDME.md file to match this behavior.


I think the poblem lies in the securityconfig file, we only secure the "show"-parts not the others. I will refactor/rename the urls so it works. I think we missed this bug earlier.

**Comment by helenahalldiniths** [comment]
I will accept this for now and make a new issue that fixes this bug (since it doesn't have to do with the work you have done here - I just happend to find it while reviewing this code)

**Review by helenahalldiniths — APPROVED** [review]

**Pull request merged**
