### PR TITLE
Issue70 .dockerignore

### LINKED ISSUE #70: Dockerignore file
Create a dockerignore from a java template

### PR DESCRIPTION
**Pull request by FelixJacobsen**
Fix #70

### CODE REVIEW

**Review by helenahalldiniths — COMMENTED** [review]
I remember that there were some discutions about first ignoring an entire folder and then "not ignoring" some. Is this the right way to do it?

In the storm project the following is ignored:
target/
.github/
.idea/

**Comment by FelixJacobsen** [comment]
> Yes I believe it is. target, we don't need anything from from those folders you mentioned. README.md and gitignore is also not a part of the docker build. 
These rows will ignore our tests since they should be executed before we make a docker image. 
image


How about replacing this with src/test/ ?

**Comment by FelixJacobsen** [comment]
It was Martin who made that solution with the src folder. I was draft this for now so I can make sure it works without any problems.

**Comment by FelixJacobsen** [comment]
Removed target folder to be ignored. We can add thiis once again if we create a multistage dockerfile build.

**Review by helenahalldiniths — APPROVED** [review]
Good job!

**Pull request merged**
