### PR TITLE
MySQL Issue 33

### LINKED ISSUE #33: Setup MySQL database
We are currently using H2 database which is good for testing but later we want to switch to MySQL.

Helena found good information here:
https://spring.io/guides/gs/accessing-data-mysql/

### PR DESCRIPTION
**Pull request by LordRekishi**
Fix #33 

Change H2 database to MySQL
Added dependency, properties and updated readme

### CODE REVIEW

**Comment by LordRekishi** [comment]
Since we created the docker image of MySQL manually we need to change this to be created in the docker image

**Comment by LordRekishi** [comment]
In order for this to work we'll need to implement [Test Containers](https://www.testcontainers.org/quickstart/junit_5_quickstart/)

**Comment by LordRekishi** [comment]
Removed the default Spring Boot test, since we should exchange this with proper unit tests in the future anyway. This makes it so we can merge in and use MySQL.

The plan when we make unit tests and integration tests should be to also update the workflow github actions to just run unit tests when doing a pull request.

**Comment by LordRekishi** [comment]
FYI, when the database is changed you will have to locally run the MySQL server as a docker container following the instructions in README

**Comment by helenahalldiniths** [comment]
> Removed the default Spring Boot test, since we should exchange this with proper unit tests in the future anyway. This makes it so we can merge in and use MySQL.
> 
> The plan when we make unit tests and integration tests should be to also update the workflow github actions to just run unit tests when doing a pull request.

Maybe this should be done in a separate issue? (Removing the default spring boot test).

**Comment by LordRekishi** [comment]
> > Removed the default Spring Boot test, since we should exchange this with proper unit tests in the future anyway. This makes it so we can merge in and use MySQL.
> > The plan when we make unit tests and integration tests should be to also update the workflow github actions to just run unit tests when doing a pull request.
> 
> Maybe this should be done in a separate issue? (Removing the default spring boot test).

Sounds good!

**Comment by LordRekishi** [comment]
How are we feeling about implementing MySQL before v1.0.0 release? @HelenaHalldinITHS @FelixJacobsen

**Comment by LordRekishi** [comment]
With docker-compose.yml (#53) implementing MySQL will be quite easy and only require one command to start up all together

**Comment by LordRekishi** [comment]
Need to update this to work with docker-compose

**Comment by FelixJacobsen** [comment]
Worked locally for me when following the README.md

**Review by FelixJacobsen — APPROVED** [review]

**Pull request merged**
