### PR TITLE
Create dependabot.yml

### LINKED ISSUE #9: Enable Dependabot
Enable checking maven and dependencies

### PR DESCRIPTION
**Pull request by FelixJacobsen**
Fix #9 

Enabled dependabot in repository settings and created this dependabot.yml file that does checks daily.

### CODE REVIEW

**Review by helenahalldiniths — COMMENTED** [review]
I think this file should be directly in the .github folder (not workflow).
https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/enabling-and-disabling-dependabot-version-updates

**Comment by LordRekishi** [comment]
> I think this file should be directly in the .github folder (not workflow). https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/enabling-and-disabling-dependabot-version-updates

Yes you are right, I double-checked the "storm" repository and it was directly in the .github directory.

**Review by LordRekishi — DISMISSED** [review]
Move dependabot.yml to the .github directory instead of the sub directory of workflows

**Comment by FelixJacobsen** [comment]
@LordRekishi I can't make any changes on Github since your request makes the entire file empty

**Review by helenahalldiniths — APPROVED** [review]
Good job

**Pull request merged**
