### PR TITLE
Relocate images folder

### LINKED ISSUE #110: Relocate images into static folder in resources
When working with Thymeleaf pictures, .css files etc should be located in the provided static folder.

### PR DESCRIPTION
**Pull request by FelixJacobsen**
Fix #111 

Also removed unnecessary main.css file since we will be using bootstrap to design our .html templates

### CODE REVIEW

**Comment by LordRekishi** [comment]
Which Issue is this connected to? And why do we want to do this?

**Comment by LordRekishi** [comment]
Is this something we need to do for your frontend to work? Or what's the reasoning behind this?

**Comment by FelixJacobsen** [comment]
Not required but the static folder is made to have pictures,css files etc.

**Comment by LordRekishi** [comment]
> Not required but the static folder is made to have pictures,css files etc.

Ok, sounds good!

**Review by LordRekishi — APPROVED** [review]

**Pull request merged**
