### PR TITLE
Crime

### LINKED ISSUE #3: Create Crime
Create entity, repository, service and controller (CURD operations)

### PR DESCRIPTION
**Pull request by LordRekishi**
Fix #3

### CODE REVIEW

**Review by helenahalldiniths — APPROVED** [review]
Looks good!
In the draft we hade a field for location ("plats"). I think we can add it later on if we want, this looks good for now!

**Review by helenahalldiniths — CHANGES_REQUESTED** [review]
I just realized you are using IntelliJ standard getters and setters (and not the setter template "build"). I think we should use the same for the hole project.

**Comment by LordRekishi** [comment]
> I just realized you are using IntelliJ standard getters and setters (and not the setter template "build"). I think we should use the same for the hole project.

How do you change template?

**Comment by helenahalldiniths** [comment]
Skärmavbild 2022-03-08 kl  18 56 26

At the top, under "setter template"!

**Review by helenahalldiniths — APPROVED** [review]
Perfect!

**Pull request merged**
